"""Generate a ``providers.toml`` from the current ``NVIDIA_*`` environment.

Migration aid for moving off the single-provider env configuration onto the
declarative multi-provider file. Reads the environment via
:func:`llmproxy.config.load_settings` (so it honours ``.env``), emits the legacy
NVIDIA provider as a filled-in ``[[provider]]`` block, and appends commented
stubs for the other supported provider types.

Usage::

    python -m llmproxy.scripts.env_to_toml [output_path] [--force]

Defaults to writing ``providers.toml`` and refuses to overwrite an existing file
unless ``--force`` is given. Pass ``-`` as the output path to write the TOML to
**stdout** instead (handy from inside Docker, where the host filesystem may not be
writable):

    docker compose run --rm --no-TTY llmproxy \\
        python -m llmproxy.scripts.env_to_toml - > providers.toml

Secrets are emitted as ``${ENV_VAR}`` references, not inlined, so the file stays
safe to commit.
"""

import os
import sys

from ..config import load_settings


def _toml_str(value):
    """Render a Python string as a double-quoted TOML string."""
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _models_array(models):
    """Render a list of ``(id, alias)`` tuples as a TOML array."""
    items = []
    for model_id, alias in models:
        if alias:
            items.append(f'  {{ id = {_toml_str(model_id)}, alias = {_toml_str(alias)} }}')
        else:
            items.append(f'  {_toml_str(model_id)}')
    if not items:
        return "[]"
    return "[\n" + ",\n".join(items) + ",\n]"


_STUBS = """
# --- Additional provider stubs (uncomment and fill in as needed) -------------
# Exposed model names are always "<provider>:<model>"; set an "alias" per model
# to override that (e.g. to disambiguate the same model served by two providers).

# [[provider]]
# name = "openai"
# type = "openai"                       # base_url defaults to https://api.openai.com/v1
# api_key = "${OPENAI_API_KEY}"
# models = ["gpt-4o", "gpt-4o-mini"]

# [[provider]]
# name = "cerebras"
# type = "openai_compatible"
# base_url = "https://api.cerebras.ai/v1"
# api_key = "${CEREBRAS_API_KEY}"
# models = [{ id = "llama-3.3-70b", alias = "fast-70b" }]

# [[provider]]
# name = "anthropic"
# type = "anthropic"                    # base_url defaults to https://api.anthropic.com
# api_key = "${ANTHROPIC_API_KEY}"
# max_tokens = 4096                     # Anthropic requires a max_tokens; this is the default
# models = ["claude-opus-4-8", "claude-sonnet-5"]

# [[provider]]
# name = "gemini"
# type = "gemini"                       # base_url defaults to the v1beta generativelanguage API
# api_key = "${GEMINI_API_KEY}"
# models = ["gemini-2.5-pro", "gemini-2.5-flash"]

# [[provider]]
# name = "azure"
# type = "azure"
# base_url = "https://YOUR-RESOURCE.openai.azure.com"
# api_key = "${AZURE_OPENAI_API_KEY}"
# api_version = "2024-02-01"
# models = ["gpt-4o"]                   # model id == Azure deployment name
"""


def render(settings):
    """Render the full ``providers.toml`` text from a loaded :class:`Settings`."""
    lines = [
        "# providers.toml — generated by `python -m llmproxy.scripts.env_to_toml`",
        "# Point llmproxy at this file via PROVIDERS_CONFIG (default: providers.toml).",
        "",
    ]
    for cfg in settings.providers:
        lines.append("[[provider]]")
        lines.append(f"name = {_toml_str(cfg.name)}")
        lines.append(f"type = {_toml_str(cfg.type)}")
        if cfg.base_url:
            lines.append(f"base_url = {_toml_str(cfg.base_url)}")
        lines.append('api_key = "${NVIDIA_API_KEY}"')
        lines.append(f"models = {_models_array(cfg.models)}")
        if cfg.embeddings_models:
            lines.append(f"embeddings_models = {_models_array(cfg.embeddings_models)}")
        lines.append("")
    return "\n".join(lines) + _STUBS


def main(argv=None):
    argv = list(sys.argv[1:] if argv is None else argv)
    force = "--force" in argv
    argv = [a for a in argv if a != "--force"]
    out_path = argv[0] if argv else "providers.toml"

    settings = load_settings()
    text = render(settings)

    # "-" streams the TOML to stdout (info line goes to stderr so stdout stays
    # clean for redirection, e.g. from inside a Docker container).
    if out_path == "-":
        sys.stdout.write(text)
        print(f"rendered {len(settings.providers)} provider block(s) to stdout", file=sys.stderr)
        return 0

    if os.path.exists(out_path) and not force:
        print(f"refusing to overwrite existing {out_path} (pass --force)", file=sys.stderr)
        return 1

    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write(text)
    print(f"wrote {out_path} ({len(settings.providers)} provider block(s)); "
          f"review it, then run with PROVIDERS_CONFIG={out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
